# Generated by Django 6.0.1 on 2026-01-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vehicle_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportjob',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_job', to='accounts.order'),
        ),
    ]
