# Generated by Django 6.0.1 on 2026-01-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_transportjob_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportjob',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_jobs', to='accounts.vehicle'),
        ),
    ]
