# Generated by Django 6.0.1 on 2026-01-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_transportjob_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporterrating',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.transportjob'),
        ),
    ]
