# Generated by Django 6.0.1 on 2026-08-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_earningsrecord_paymentsplit_refundrequest_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
